### ISSUE TITLE
SSLv3 alert handshake failure with cf-d v5.4.0

### ISSUE THREAD

**Issue by bgandon** [pivotal-cf/cf-rabbitmq-smoke-tests-release#3]
Hi there,

When running the smoke tests, I get this error:

```
2018-11-13T14:09:36.44+0000 [APP/PROC/WEB/0] ERR == Sinatra (v2.0.1) has taken the stage on 8080 for production with backup from Thin  
2018-11-13T14:09:38.98+0000 [CELL/0] OUT Container became healthy  
2018-11-13T14:10:00.14+0000 [APP/PROC/WEB/0] ERR 2018-11-13 14:10:00 - StandardError - [ERROR] Store::write: SSL_connect returned=1 errno=0 state=unknown state: sslv3 alert handshake failure.:  
2018-11-13T14:10:00.14+0000 [APP/PROC/WEB/0] ERR 	/home/vcap/app/lib/store.rb:18:in `rescue in write'  
2018-11-13T14:10:00.14+0000 [APP/PROC/WEB/0] ERR 	/home/vcap/app/lib/store.rb:21:in `write'  
2018-11-13T14:10:00.14+0000 [APP/PROC/WEB/0] ERR 	/home/vcap/app/lib/server.rb:58:in `block in <class:Server>'  
```

Here are the versions I'm running:
```yaml
cf_deployment_version: 5.4.0
rabbitmq_release_version: "252.0.0"
rabbitmq_broker_version: "37.0.0"
rabbitmq_smoke_tests_version: "19.0.0"
```

Maybe the smoke tests are not compatible with recent Ruby buildpacks?

There is also a cleanup issue for which I'll submit a PR. (edit: this now submitted as #4)

Best,
Benjamin

**Comment by bgandon** [comment]
Hi Zoe @zvance!
Can someone from the team have a look at this blocking issue please?

**Comment by blgm** [comment]
Hi @bgandon, this isn't an error that we have seen before.  Has it ever worked for you?  What version of the Ruby buildpack are you using?  I've just seen it work with v1.7.24.

**Comment by blgm** [comment]
Hi @bgandon, I'm closing this because it seems to have gone stale.  If you're still seeing the issue, then please re-open.

**Comment by martjarvi** [comment]
hi, getting the same error with ruby-buildpack-v1.7.34, when using cf-deployment 7.9
